### ISSUE TITLE
learn clap library ,and use it for us 

### ISSUE THREAD

**Issue by zuowenjian** [xcodecraft/rigger#5]
clap is cli argument  parser  library.

as:
/rg/src/cmds/conf.rs
/rg/src/cmds/start.rs

**Comment by baoyachi** [comment]
doing

**Comment by zuowenjian** [comment]
How is the work progressing?

**Comment by baoyachi** [comment]
start working

**Comment by baoyachi** [comment]
# remark
cli use in18 . but ,i don't  how to get system language in rust

**Comment by zuowenjian** [comment]
Do you have some code for push ?

**Comment by baoyachi** [comment]
I‘m not in this group，I just fork a branch in my oner project

**Comment by baoyachi** [comment]
the clap is easy to config command with .yaml file
